# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

resources:
  repositories:
  - repository: main
    type: git
    name: https://github.com/Joel981/master-projectrepo.git
    ref: refs/heads/main
  - repository: repo1
    type: git
    name: https://github.com/Joel981/project1.git
    ref: refs/heads/main
  - repository: repo2
    type: git
    name: https://github.com/Joel981/Project2.git
    ref: refs/heads/main
  # add more repositories as needed
jobs:
- job: update-yaml-files
  steps:
  - checkout: main
  - script: |
      # set the path to the YAML files relative to the root of the repository
      yaml_path="workflow/sampleyaml.yml"
      # update the YAML files in the other repositories
      for main in repo1 repo2; do
        git clone --branch main $(eval echo $"$(echo ${{resources.repositories.${main}.repository}}))" $main
        cp $yaml_path $main
        cd $main
        git add $yaml_path
        git commit -m "Update YAML files from main repository"
        git push
        cd ..
        rm -rf $main
      done