trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      git config --global user.email "joelantowilliams@.com"
      git config --global user.name "Joelanto"

      git clone https://github.com/Joel981/master-projectrepo.git
      # Navigate to the directory where the file to be copied is located
      cd master-projectrepo/workflow/
      # Copy the file(s) to a temporary directory
      cp sampleyaml.yml /tmp/
      # Navigate to the destination repository
      cd master-projectrepo/workflow/
      # Copy the file(s) from the temporary directory to the destination repository
      cp /tmp/sampleyaml.yml
      # Commit and push the changes
      git add sampleyaml.yml
      git commit -m "Copy file from source to destination repository"
      git push origin main